(() => {
  'use strict';
  const api=['localhost','127.0.0.1'].includes(location.hostname)?'http://127.0.0.1:8787':'https://api.ahmadaldarwish.com';
  const $=id=>document.getElementById(id);
  const keys=['fajr','sunrise','dhuhr','asr','maghrib','isha'];
  const texts={
    ar:{brand:'وَصْل',title:'مواقيت الصلاة',next:'الصلاة القادمة',choose:'اختر مدينتك',prompt:'اختر مدينتك لعرض مواقيت الصلاة.',names:['الفجر','الشروق','الظهر','العصر','المغرب','العشاء'],settings:'الإعدادات',search:'بحث',city:'اسم المدينة',close:'إغلاق',language:'اللغة',appearance:'المظهر',light:'فاتح',dark:'داكن',clock:'تنسيق الوقت',hours12:'12 ساعة',hours24:'24 ساعة',back:'العودة إلى وَصْل',credit:'بيانات المدن: ',loading:'جارٍ تحميل المواقيت…',error:'تعذّر تحميل المواقيت. تحقق من الاتصال وأعد المحاولة.',retry:'إعادة المحاولة',today:'اليوم',previous:'اليوم السابق',following:'اليوم التالي',remaining:'متبقي',h:'س',m:'د',s:'ث',tomorrow:'غداً',estimated:'مواقيت تقديرية؛ تعذّر الحصول على الجدول الرسمي لهذا اليوم.',unavailable:'بعض المواقيت غير متاحة لهذا الموقع والتاريخ.',empty:'لم نجد مدينة بهذا الاسم. جرّب كتابة الاسم بالإنجليزية.',searchError:'تعذّر البحث عن المدينة. جرّب مجدداً.',note:'يجري البحث عن المدن وحساب المواقيت على خادم وَصْل، دون نشر قواعد الحساب.',settingsNote:'المواقيت حسب الموقع المختار. قد تختلف عن التطبيق إذا غيّرت إعدادات الحساب فيه.',historical:'مواقيت اليوم المختار',service:'مواقيت الصلاة حسب التوقيت المحلي للمدينة.'},
    en:{brand:'Wasl',title:'Prayer times',next:'Next prayer',choose:'Choose your city',prompt:'Choose your city to see prayer times.',names:['Fajr','Sunrise','Dhuhr','Asr','Maghrib','Isha'],settings:'Settings',search:'Search',city:'City name',close:'Close',language:'Language',appearance:'Appearance',light:'Light',dark:'Dark',clock:'Time format',hours12:'12 hour',hours24:'24 hour',back:'Back to Wasl',credit:'City data: ',loading:'Loading prayer times…',error:'Unable to load prayer times. Check your connection and retry.',retry:'Retry',today:'Today',previous:'Previous day',following:'Next day',remaining:'Remaining',h:'h',m:'m',s:'s',tomorrow:'Tomorrow',estimated:'Estimated times; the official timetable could not be obtained for this date.',unavailable:'Some times are unavailable for this location and date.',empty:'No matching city. Try another spelling.',searchError:'City search is unavailable. Please retry.',note:'City searches and prayer calculations run on Wasl’s server; its calculation rules remain private.',settingsNote:'Times use the selected location. They may differ from the phone app if you changed its calculation settings.',historical:'Selected day',service:'Prayer times in the selected city’s local time.'},
    de:{brand:'Wasl',title:'Gebetszeiten',next:'Nächstes Gebet',choose:'Stadt auswählen',prompt:'Wähle deine Stadt, um die Gebetszeiten anzuzeigen.',names:['Fadschr','Sonnenaufgang','Dhuhr','Asr','Maghrib','Ischa'],settings:'Einstellungen',search:'Suchen',city:'Stadtname',close:'Schließen',language:'Sprache',appearance:'Darstellung',light:'Hell',dark:'Dunkel',clock:'Zeitformat',hours12:'12 Stunden',hours24:'24 Stunden',back:'Zurück zu Wasl',credit:'Stadtdaten: ',loading:'Gebetszeiten werden geladen…',error:'Gebetszeiten konnten nicht geladen werden. Prüfe die Verbindung und versuche es erneut.',retry:'Erneut versuchen',today:'Heute',previous:'Vorheriger Tag',following:'Nächster Tag',remaining:'Verbleibend',h:'Std.',m:'Min.',s:'Sek.',tomorrow:'Morgen',estimated:'Geschätzte Zeiten; der offizielle Kalender war für dieses Datum nicht verfügbar.',unavailable:'Einige Zeiten sind für diesen Ort und dieses Datum nicht verfügbar.',empty:'Keine passende Stadt gefunden. Versuche eine andere Schreibweise.',searchError:'Die Stadtsuche ist nicht verfügbar. Bitte versuche es erneut.',note:'Stadtsuche und Gebetsberechnung erfolgen auf dem Wasl-Server; die Berechnungsregeln bleiben privat.',settingsNote:'Die Zeiten gelten für den ausgewählten Ort. Bei anderen Berechnungseinstellungen in der App können sie abweichen.',historical:'Ausgewählter Tag',service:'Gebetszeiten in der Ortszeit der ausgewählten Stadt.'}
  };
  const extras={ar:{gps:'استخدم موقعي الحالي',gpsNote:'يُرسل موقعك إلى خادم وَصْل لحساب المواقيت. لا يُحفظ في سجل الخادم.',finding:'جارٍ تحديد موقعك…',denied:'لم يُسمح بالوصول إلى الموقع. يمكنك اختيار المدينة يدوياً.',gpsError:'تعذّر تحديد موقعك. فعّل خدمة الموقع أو اختر مدينتك يدوياً.',install:'ثبّت تطبيق الويب',installHelp:'من قائمة المتصفح، اختر «إضافة إلى الشاشة الرئيسية» أو «تثبيت التطبيق». على iPhone، استخدم زر المشاركة في Safari ثم «إضافة إلى الشاشة الرئيسية».'},en:{gps:'Use my current location',gpsNote:'Your coordinates are sent to Wasl’s server to calculate times. They are not saved in server logs.',finding:'Finding your location…',denied:'Location access was denied. You can choose a city manually.',gpsError:'Unable to find your location. Enable location services or choose a city manually.',install:'Install web app',installHelp:'In your browser menu, choose Add to Home screen or Install app. On iPhone, use Safari’s Share button, then Add to Home Screen.'},de:{gps:'Aktuellen Standort verwenden',gpsNote:'Deine Koordinaten werden zur Berechnung an den Wasl-Server gesendet und nicht in Serverprotokollen gespeichert.',finding:'Standort wird ermittelt…',denied:'Standortzugriff wurde abgelehnt. Wähle deine Stadt manuell.',gpsError:'Standort nicht verfügbar. Aktiviere die Ortung oder wähle deine Stadt manuell.',install:'Web-App installieren',installHelp:'Wähle im Browsermenü Zum Startbildschirm hinzufügen oder App installieren. Auf dem iPhone: Safari → Teilen → Zum Home-Bildschirm.'}};
  let installPrompt=null;
  const get=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
  const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
  let lang;try{lang=localStorage.getItem('preferredLang');}catch{}if(!texts[lang])lang='ar';
  let theme;try{theme=localStorage.getItem('preferredTheme');}catch{}if(!['light','dark'].includes(theme))theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';
  let clock=get('waslWebClock','12'),city=get('waslWebCity',null),day=null,data=null,loadId=0,controller=null,searchId=0,state='prompt',followToday=true;
  const rows=[...document.querySelectorAll('.prayer-row')];
  const cityName=()=>{const names={DE:{'ميونخ':['ميونخ','Munich','München'],'München':['ميونخ','Munich','München']},IQ:{'بغداد':['بغداد','Baghdad','Bagdad'],'Baghdad':['بغداد','Baghdad','Bagdad']},SA:{'مكة المكرمة':['مكة المكرمة','Makkah','Mekka'],'Makkah':['مكة المكرمة','Makkah','Mekka']},TR:{'إسطنبول':['إسطنبول','Istanbul','Istanbul'],'Istanbul':['إسطنبول','Istanbul','Istanbul']}};return names[city?.country]?.[city?.name]?.[['ar','en','de'].indexOf(lang)]||city?.name;};
  function localDay(zone){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(p=>[p.type,p.value]));return `${parts.year}-${parts.month}-${parts.day}`;}
  function shift(date,n){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
  const time=value=>{if(!value)return '—:—';const parts=new Intl.DateTimeFormat(lang==='ar'?'ar-u-nu-latn':lang,{timeZone:city.zone,hour:'numeric',minute:'2-digit',hour12:clock==='12'}).formatToParts(new Date(value));if(lang==='ar'){const period=parts.find(p=>p.type==='dayPeriod')?.value;const digits=parts.filter(p=>['hour','minute','literal'].includes(p.type)).map(p=>p.value).join('').trim();return period?'\u2067'+period+'\u2069 \u2066'+digits+'\u2069':digits;}return parts.map(p=>p.value).join('');};
  function status(message){$('status').textContent=message;}
  function dateHeading(){if(!day||!city){$('day-title').textContent=texts[lang].title;$('gregorian-date').textContent='';return;}const instant=new Date(day+'T12:00:00Z');$('day-title').textContent=new Intl.DateTimeFormat(lang+'-u-ca-islamic-umalqura',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(instant);$('gregorian-date').textContent=new Intl.DateTimeFormat(lang,{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(instant);}
  function translate(){const t=texts[lang];$('gps-button').textContent=extras[lang].gps;$('gps-note').textContent=extras[lang].gpsNote;$('install-button').textContent=extras[lang].install;$('install-help').textContent='';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.title=t.title+' | '+t.brand;document.querySelector('.brand span').textContent=t.brand;
    for(const [id,value] of Object.entries({'next-title':t.next,'next-name':t.title,'city-label':cityName()||t.choose,'location-title':t.choose,'settings-title':t.settings,'search-label':t.city,'search-submit':t.search,'language-label':t.language,'appearance-label':t.appearance,'clock-label':t.clock,'back-link':t.back,'city-credit':t.credit,'retry':t.retry,'today-button':t.today,'location-note':t.note,'settings-note':t.settingsNote}))$(id).textContent=value;
    $('settings-button').setAttribute('aria-label',t.settings);$('previous-day').setAttribute('aria-label',t.previous);$('next-day').setAttribute('aria-label',t.following);document.querySelectorAll('.close-dialog').forEach(b=>b.setAttribute('aria-label',t.close));
    $('appearance').options[0].textContent=t.light;$('appearance').options[1].textContent=t.dark;$('clock-format').options[0].textContent=t.hours12;$('clock-format').options[1].textContent=t.hours24;
    rows.forEach((row,i)=>row.querySelector('h3').textContent=t.names[i]);$('language').value=lang;$('appearance').value=theme;$('clock-format').value=clock;
    document.documentElement.dataset.theme=theme;document.querySelector('meta[name=theme-color]').content=theme==='dark'?'#1b292f':'#1769be';
    $('popular-cities').replaceChildren();for(const c of [{name:lang==='ar'?'ميونخ':'München',lat:48.137154,lng:11.576124,zone:'Europe/Berlin',country:'DE'},{name:lang==='ar'?'بغداد':'Baghdad',lat:33.34058,lng:44.40088,zone:'Asia/Baghdad',country:'IQ'},{name:lang==='ar'?'مكة المكرمة':'Makkah',lat:21.426666,lng:39.831666,zone:'Asia/Riyadh',country:'SA'},{name:lang==='ar'?'إسطنبول':'Istanbul',lat:41.0082,lng:28.9784,zone:'Europe/Istanbul',country:'TR'}]){const b=document.createElement('button');b.textContent=c.name;b.addEventListener('click',()=>choose(c));$('popular-cities').append(b);}
    if(data)render();else{dateHeading();status(t[state]||t.prompt);document.querySelector('.countdown').textContent=t.prompt;}
  }
  function render(){const t=texts[lang];rows.forEach((row,i)=>row.querySelector('time').textContent=time(data.times[keys[i]]));dateHeading();$('today-button').hidden=day===localDay(city.zone);status((data.source==='estimated'||data.tomorrowSource==='estimated')?t.estimated:keys.some(k=>!data.times[k])?t.unavailable:t.service);tick();}
  function tick(){if(!data||!city)return;const t=texts[lang],now=Date.now(),currentDay=localDay(city.zone);if(day!==currentDay){$('next-title').textContent=t.historical;$('next-name').textContent=t.title;document.querySelector('.next-time').textContent='—:—';document.querySelector('.countdown').textContent=$('gregorian-date').textContent;rows.forEach(r=>r.classList.remove('active'));return;}
    const list=keys.filter(k=>k!=='sunrise').map(k=>({key:k,value:data.times[k]})).filter(p=>p.value&&Date.parse(p.value)>now);let next=list[0],isTomorrow=false;
    if(!next&&data.tomorrow.fajr){next={key:'fajr',value:data.tomorrow.fajr};isTomorrow=true;}if(!next){$('next-name').textContent=t.title;document.querySelector('.next-time').textContent='—:—';document.querySelector('.countdown').textContent=t.unavailable;return;}
    $('next-title').textContent=t.next;$('next-name').textContent=t.names[keys.indexOf(next.key)];document.querySelector('.next-time').textContent=time(next.value);
    const seconds=Math.max(0,Math.floor((Date.parse(next.value)-now)/1000)),h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;
    document.querySelector('.countdown').textContent=`${isTomorrow?t.tomorrow+' · ':''}${t.remaining} ${h} ${t.h} ${m} ${t.m} ${s} ${t.s}`;
    rows.forEach((row,i)=>row.classList.toggle('active',keys[i]===next.key));
    const start=Date.parse(data.times.fajr),end=Date.parse(data.times.isha),fraction=Number.isFinite(start)&&end>start?Math.min(1,Math.max(0,(now-start)/(end-start))):0;
    document.querySelector('.arc-fill').style.strokeDasharray=`${fraction} 1`;
    document.querySelectorAll('[data-prayer]').forEach(node=>{const timestamp=Date.parse(data.times[node.dataset.prayer]);node.classList.toggle('sun',Number.isFinite(timestamp)&&timestamp<=now);node.classList.toggle('next-dot',node.dataset.prayer===next.key);});
  }
  async function load(){if(!city)return;const id=++loadId;controller?.abort();controller=new AbortController();data=null;document.querySelector('.arc-fill').style.strokeDasharray='0 1';document.querySelectorAll('[data-prayer]').forEach(n=>n.classList.remove('sun','next-dot'));state='loading';status(texts[lang].loading);$('retry').hidden=true;rows.forEach(r=>{r.querySelector('time').textContent='—:—';r.classList.remove('active');});$('next-name').textContent=texts[lang].title;document.querySelector('.next-time').textContent='—:—';document.querySelector('.countdown').textContent=texts[lang].loading;dateHeading();
    try{const params=new URLSearchParams({lat:city.lat,lng:city.lng,zone:city.zone,country:city.country,city:city.name,date:day});const response=await fetch(api+'/v1/times?'+params,{signal:controller.signal});if(!response.ok)throw Error();const result=await response.json();if(id!==loadId)return;if(!result.times||!result.tomorrow)throw Error();data=result;state='service';render();}
    catch(e){if(id!==loadId||e.name==='AbortError')return;state='error';status(texts[lang].error);document.querySelector('.countdown').textContent=texts[lang].error;$('retry').hidden=false;}
  }
  function choose(c){city={...c,name:c.name};save('waslWebCity',city);day=localDay(city.zone);followToday=true;$('city-label').textContent=city.name;$('location-dialog').close();load();}
  $('gps-button').addEventListener('click',()=>{const button=$('gps-button');if(!navigator.geolocation){$('search-status').textContent=extras[lang].gpsError;return;}button.disabled=true;$('search-status').textContent=extras[lang].finding;navigator.geolocation.getCurrentPosition(async position=>{try{const params=new URLSearchParams({lat:position.coords.latitude,lng:position.coords.longitude,lang});const response=await fetch(api+'/v1/location?'+params);if(!response.ok)throw Error();const result=await response.json();choose(result.city);}catch{$('search-status').textContent=extras[lang].gpsError;}finally{button.disabled=false;}},error=>{button.disabled=false;$('search-status').textContent=error.code===1?extras[lang].denied:extras[lang].gpsError;},{enableHighAccuracy:true,timeout:15000,maximumAge:60000});});
  addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});
  const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone;
  $('install-button').hidden=standalone();
  addEventListener('appinstalled',()=>{installPrompt=null;$('install-button').hidden=true;});
  $('install-button').addEventListener('click',async()=>{if(installPrompt){const prompt=installPrompt;installPrompt=null;await prompt.prompt();await prompt.userChoice;}else $('install-help').textContent=extras[lang].installHelp;});
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
  $('location-button').addEventListener('click',()=>{$('search-status').textContent='';$('location-dialog').showModal();});$('settings-button').addEventListener('click',()=>$('settings-dialog').showModal());document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
  $('search-form').addEventListener('submit',async e=>{e.preventDefault();const id=++searchId;const button=$('search-submit');button.disabled=true;$('search-status').textContent=texts[lang].loading;$('city-results').replaceChildren();try{const response=await fetch(api+'/v1/cities?'+new URLSearchParams({q:$('city-search').value,lang}));if(!response.ok)throw Error();const result=await response.json();if(id!==searchId)return;$('search-status').textContent=result.cities.length?'':texts[lang].empty;for(const c of result.cities){const b=document.createElement('button');b.className='city-result';b.textContent=[c.name,c.region,c.countryName].filter(Boolean).join(' · ');b.addEventListener('click',()=>choose(c));$('city-results').append(b);}}catch{$('search-status').textContent=texts[lang].searchError;}finally{button.disabled=false;}});
  $('language').addEventListener('change',()=>{lang=$('language').value;try{localStorage.setItem('preferredLang',lang);}catch{}translate();});$('appearance').addEventListener('change',()=>{theme=$('appearance').value;try{localStorage.setItem('preferredTheme',theme);}catch{}translate();});$('clock-format').addEventListener('change',()=>{clock=$('clock-format').value;save('waslWebClock',clock);translate();});
  $('retry').addEventListener('click',load);$('today-button').addEventListener('click',()=>{day=localDay(city.zone);followToday=true;load();});$('previous-day').addEventListener('click',()=>{if(city){day=shift(day,-1);followToday=false;load();}});$('next-day').addEventListener('click',()=>{if(city){day=shift(day,1);followToday=false;load();}});
  if(city){try{day=localDay(city.zone);}catch{city=null;}}translate();if(city)load();
  function refresh(){if(city&&followToday&&day!==localDay(city.zone)){day=localDay(city.zone);load();}else tick();}
  setInterval(refresh,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
})();
